//------------------------------------------------------------------------
// Generated by Neo on 7/08/2004 18:03:36 for THOUGHTWORKS\edoernenburg
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------

using System;
using System.Data;
using Neo.Core;


namespace Movies.Model
{

public class MovieActorLink : MovieActorLinkBase
{
	protected internal MovieActorLink(System.Data.DataRow aRow, Neo.Core.ObjectContext aContext) : 
		       base(aRow, aContext)
	{
	}
		        
}

}

 	
