//------------------------------------------------------------------------
// Generated by Neo on 17/02/2004 11:21:13 for THOUGHTWORKS\edoernenburg
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------

using System;
using System.Data;
using Neo.Core;


namespace Pubs4.Model
{

	public class Discount : DiscountBase
	{
		protected Discount(System.Data.DataRow aRow, Neo.Core.ObjectContext aContext) : 
				base(aRow, aContext)
		{
		}
			        
	}

}

 	
