//------------------------------------------------------------------------
// Generated by Neo on 05/06/2003 15:05:27 for EUU\doere1
//
// This file was autogenerated but you can (and are meant to) edit it as 
// it will not be overwritten unless explicitly requested.
//------------------------------------------------------------------------

using System;
using System.Data;
using Neo.Core;


namespace Pubs4.Model
{

	public class Job : JobBase
	{
		protected Job(System.Data.DataRow aRow, Neo.Core.ObjectContext aContext) : 
				base(aRow, aContext)
		{
		}
			        
	}

}

 	
